//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnT.SongClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pt-BR")]
        public global::System.Globalization.CultureInfo Culture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pt-BR")]
        public global::System.Globalization.CultureInfo RestartCulture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["RestartCulture"]));
            }
            set {
                this["RestartCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveInstitutions {
            get {
                return ((bool)(this["HideInactiveInstitutions"]));
            }
            set {
                this["HideInactiveInstitutions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactivePoles {
            get {
                return ((bool)(this["HideInactivePoles"]));
            }
            set {
                this["HideInactivePoles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveUsers {
            get {
                return ((bool)(this["HideInactiveUsers"]));
            }
            set {
                this["HideInactiveUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveTeachers {
            get {
                return ((bool)(this["HideInactiveTeachers"]));
            }
            set {
                this["HideInactiveTeachers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveStudents {
            get {
                return ((bool)(this["HideInactiveStudents"]));
            }
            set {
                this["HideInactiveStudents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveRoles {
            get {
                return ((bool)(this["HideInactiveRoles"]));
            }
            set {
                this["HideInactiveRoles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveInstruments {
            get {
                return ((bool)(this["HideInactiveInstruments"]));
            }
            set {
                this["HideInactiveInstruments"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstitutionId,DisplayName,EntityName,LocalInitiative,Institutionalized,TaxId,Coor" +
            "dinatorName,InstitutionLocation,Phones,InstitutionSite,Email,InstitutionStatus,C" +
            "reationTime,InactivationTime,InactivationReason")]
        public string InstitutionGridColumns {
            get {
                return ((string)(this["InstitutionGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,EntityName,CoordinatorName,InstitutionLocation,Phones,InstitutionStat" +
            "us")]
        public string InstitutionGridDisplayedColumns {
            get {
                return ((string)(this["InstitutionGridDisplayedColumns"]));
            }
            set {
                this["InstitutionGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,EntityName,CoordinatorName,InstitutionLocation,Phones,InstitutionStat" +
            "us")]
        public string InstitutionGridDefaultColumns {
            get {
                return ((string)(this["InstitutionGridDefaultColumns"]));
            }
            set {
                this["InstitutionGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public decimal GridFontSize {
            get {
                return ((decimal)(this["GridFontSize"]));
            }
            set {
                this["GridFontSize"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PoleId,DisplayName,InstitutionName,PoleLocation,Phones,Email,PoleStatus,CreationT" +
            "ime,InactivationTime,InactivationReason")]
        public string PoleGridColumns {
            get {
                return ((string)(this["PoleGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,InstitutionName,PoleLocation,Phones,PoleStatus")]
        public string PoleGridDisplayedColumns {
            get {
                return ((string)(this["PoleGridDisplayedColumns"]));
            }
            set {
                this["PoleGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,InstitutionName,PoleLocation,Phones,PoleStatus")]
        public string PoleGridDefaultColumns {
            get {
                return ((string)(this["PoleGridDefaultColumns"]));
            }
            set {
                this["PoleGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TeacherId,DisplayName,Birthdate,UserLogin,Poles,TeacherLocation,Phones,Email,Acad" +
            "emicBackground,TeacherStatus,CreationTime,InactivationTime,InactivationReason")]
        public string TeacherGridColumns {
            get {
                return ((string)(this["TeacherGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,UserLogin,Poles,TeacherLocation,Phones,Email,TeacherStatus")]
        public string TeacherGridDisplayedColumns {
            get {
                return ((string)(this["TeacherGridDisplayedColumns"]));
            }
            set {
                this["TeacherGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,UserLogin,Poles,TeacherLocation,Phones,Email,TeacherStatus")]
        public string TeacherGridDefaultColumns {
            get {
                return ((string)(this["TeacherGridDefaultColumns"]));
            }
            set {
                this["TeacherGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StudentId,DisplayName,Birthdate,HasDisability,GuardianName,PoleName,UserLogin,Stu" +
            "dentLocation,Phones,Email,StudentStatus,CreationTime,InactivationTime,Inactivati" +
            "onReason")]
        public string StudentGridColumns {
            get {
                return ((string)(this["StudentGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,Birthdate,GuardianName,PoleName,StudentLocation,Phones,StudentStatus")]
        public string StudentGridDisplayedColumns {
            get {
                return ((string)(this["StudentGridDisplayedColumns"]));
            }
            set {
                this["StudentGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DisplayName,Birthdate,GuardianName,PoleName,StudentLocation,Phones,StudentStatus")]
        public string StudentGridDefaultColumns {
            get {
                return ((string)(this["StudentGridDefaultColumns"]));
            }
            set {
                this["StudentGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserId,UserName,Login,InstitutionName,RoleName,Email,UserStatus,CreationTime,Inac" +
            "tivationTime,InactivationReason")]
        public string UserGridColumns {
            get {
                return ((string)(this["UserGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserName,Login,InstitutionName,RoleName,Email,UserStatus")]
        public string UserGridDisplayedColumns {
            get {
                return ((string)(this["UserGridDisplayedColumns"]));
            }
            set {
                this["UserGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserName,Login,InstitutionName,RoleName,Email,UserStatus")]
        public string UserGridDefaultColumns {
            get {
                return ((string)(this["UserGridDefaultColumns"]));
            }
            set {
                this["UserGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstrumentId,Code,InstrumentTypeName,PoleName,InstrumentLocation,InstrumentStatus" +
            ",CreationTime,InactivationTime,InactivationReason")]
        public string InstrumentGridColumns {
            get {
                return ((string)(this["InstrumentGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Code,InstrumentTypeName,PoleName,InstrumentLocation,InstrumentStatus")]
        public string InstrumentGridDisplayedColumns {
            get {
                return ((string)(this["InstrumentGridDisplayedColumns"]));
            }
            set {
                this["InstrumentGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Code,InstrumentTypeName,PoleName,InstrumentLocation,InstrumentStatus")]
        public string InstrumentGridDefaultColumns {
            get {
                return ((string)(this["InstrumentGridDefaultColumns"]));
            }
            set {
                this["InstrumentGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUserLogin {
            get {
                return ((string)(this["LastUserLogin"]));
            }
            set {
                this["LastUserLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideInactiveClasses {
            get {
                return ((bool)(this["HideInactiveClasses"]));
            }
            set {
                this["HideInactiveClasses"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClassId,SemesterName,SubjectCode,Code,PoleName,TeacherName,AggregatedTypeName,Cla" +
            "ssLevelName,Capacity,WeekDays,StartTime,Duration,ClassStatus,CreationTime,Inacti" +
            "vationTime,InactivationReason")]
        public string ClassGridColumns {
            get {
                return ((string)(this["ClassGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Code,PoleName,TeacherName,AggregatedTypeName,ClassLevelName,WeekDays,StartTime,Cl" +
            "assStatus")]
        public string ClassGridDisplayedColumns {
            get {
                return ((string)(this["ClassGridDisplayedColumns"]));
            }
            set {
                this["ClassGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Code,PoleName,TeacherName,AggregatedTypeName,ClassLevelName,WeekDays,StartTime,Cl" +
            "assStatus")]
        public string ClassGridDefaultColumns {
            get {
                return ((string)(this["ClassGridDefaultColumns"]));
            }
            set {
                this["ClassGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegistrationId,SemesterName,ClassCode,PoleName,StudentName,AutoRenewal,Registrati" +
            "onStatus,CreationTime,InactivationTime,InactivationReason")]
        public string RegistrationGridColumns {
            get {
                return ((string)(this["RegistrationGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClassCode,PoleName,StudentName,AutoRenewal,RegistrationStatus")]
        public string RegistrationGridDisplayedColumns {
            get {
                return ((string)(this["RegistrationGridDisplayedColumns"]));
            }
            set {
                this["RegistrationGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClassCode,PoleName,StudentName,AutoRenewal,RegistrationStatus")]
        public string RegistrationGridDefaultColumns {
            get {
                return ((string)(this["RegistrationGridDefaultColumns"]));
            }
            set {
                this["RegistrationGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportId,SemesterName,PeriodName,TypeName,AuthorName,InstitutionName,ClassData,Re" +
            "portStatus")]
        public string ReportGridColumns {
            get {
                return ((string)(this["ReportGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PeriodName,TypeName,AuthorName,InstitutionName,ClassData,ReportStatus")]
        public string ReportGridDisplayedColumns {
            get {
                return ((string)(this["ReportGridDisplayedColumns"]));
            }
            set {
                this["ReportGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PeriodName,TypeName,AuthorName,InstitutionName,ClassData,ReportStatus")]
        public string ReportGridDefaultColumns {
            get {
                return ((string)(this["ReportGridDefaultColumns"]));
            }
            set {
                this["ReportGridDefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EventId,EventDate,EventTime,EventName,InstitutionName,EventLocation,Duration,Desc" +
            "ription,EventSendOptionName,CreationTime")]
        public string EventGridColumns {
            get {
                return ((string)(this["EventGridColumns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EventDate,EventTime,EventName,InstitutionName,EventLocation,Duration,Description")]
        public string EventGridDisplayedColumns {
            get {
                return ((string)(this["EventGridDisplayedColumns"]));
            }
            set {
                this["EventGridDisplayedColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EventDate,EventTime,EventName,InstitutionName,EventLocation,Duration,Description")]
        public string EventGridDefaultColumns {
            get {
                return ((string)(this["EventGridDefaultColumns"]));
            }
            set {
                this["EventGridDefaultColumns"] = value;
            }
        }
    }
}
